### ISSUE TITLE
Error running against a Azure WIN2012R2 VM

### ISSUE THREAD

**Issue by burdena** [dev-sec/windows-patch-baseline#8]
Inspec 1.29.0

2017-06-28T05:59:59+00:00] WARN: URL target https://github.com/dev-sec/windows-patch-baseline transformed to https://github.com/dev-sec/windows-patch-baseline/archive/master.tar.gz. Consider using the git fetcher
libraries/windows_updates.rb:18:in `[]': no implicit conversion of String into Integer (TypeError)
	from libraries/windows_updates.rb:18:in `title'
	from libraries/windows_updates.rb:42:in `to_s'
	from /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/metadata.rb:180:in `build_description_from'
	from /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/metadata.rb:133:in `populate'
	from /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/metadata.rb:258:in `create'
	from /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:420:in `set_it_up'
	from /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:384:in `subclass'
	from /usr/local/bundle/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:258:in `block in define_example_group_method'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/runner_rspec.rb:27:in `example_group'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/runner.rb:243:in `get_check_example'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/runner.rb:269:in `block in register_rule'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/runner.rb:268:in `each'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/runner.rb:268:in `flat_map'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/runner.rb:268:in `register_rule'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/runner.rb:94:in `block in load'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/runner.rb:93:in `each'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/runner.rb:93:in `load'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/runner.rb:100:in `run'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/base_cli.rb:83:in `run_tests'
	from /usr/local/bundle/gems/inspec-1.25.1/lib/inspec/cli.rb:166:in `exec'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/bundle/gems/inspec-1.25.1/bin/inspec:12:in `<top (required)>'
	from /usr/local/bundle/bin/inspec:22:in `load'
	from /usr/local/bundle/bin/inspec:22:in `<main>'

**Comment by burdena** [comment]
I've raised a pull request to fix this issue

**Comment by TeunRoefs** [comment]
@burdena This does not seem to work for me, I get empty `@data[0]['Title']` fields. Any idea what might cause this? Running the underlying powershell scripts shows `Title` in the result.
